# Generated by Django 5.2.18 on 2026-10-08 17:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_share_percent', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('surplus_window_months', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_months_for_estimate', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('full_confidence_months', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('emergency_fund_months', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('liquid_horizon_months', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('low_risk_max', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('min_balance', models.BigIntegerField(default=100000, validators=[django.core.validators.MinValueValidator(0)])),
                ('backtest_months', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'rule configuration',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paused', 'Paused')], default='proposed', max_length=10)),
                ('monthly_amount', models.BigIntegerField()),
                ('proposed_amount', models.BigIntegerField(help_text='Rule-engine amount; edits may only lower it.')),
                ('median_surplus', models.BigIntegerField(blank=True, null=True)),
                ('median_expenses', models.BigIntegerField()),
                ('months_of_data', models.PositiveSmallIntegerField()),
                ('confidence', models.CharField(choices=[('none', 'none'), ('low', 'low'), ('normal', 'normal')], max_length=10)),
                ('created_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=10)),
                ('max_monthly_amount', models.BigIntegerField()),
                ('min_balance', models.BigIntegerField()),
                ('per_transfer_approval', models.BooleanField()),
                ('signed_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='banking.product')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mandate', to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('mandate_version', models.PositiveIntegerField(blank=True, null=True)),
                ('clause', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('monthly_amount', models.BigIntegerField()),
                ('target_amount', models.BigIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.plan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.PositiveSmallIntegerField()),
                ('existing_emergency_fund', models.BigIntegerField()),
                ('expected_monthly_savings', models.BigIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.questionnaireanswer'),
        ),
        migrations.CreateModel(
            name='ExpenseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('due_on', models.DateField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='plans.questionnaireanswer')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=10)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='plans.mandate')),
                ('plan_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='plans.planitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.product')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of the month this execution belongs to.')),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('executed', 'Executed'), ('denied', 'Denied'), ('awaiting_approval', 'Awaiting Approval')], max_length=20)),
                ('amount', models.BigIntegerField()),
                ('mandate_version', models.PositiveIntegerField()),
                ('clause', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='plans.recurringorder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mandate',
            constraint=models.UniqueConstraint(fields=('customer', 'version'), name='mandate_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='planitem',
            constraint=models.UniqueConstraint(fields=('plan', 'position'), name='plan_item_position_unique'),
        ),
    ]
