# Generated by Django 5.2.18 on 2026-10-08 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Current account', max_length=100)),
                ('balance', models.BigIntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('risk_level', models.PositiveSmallIntegerField(help_text='1 (lowest) to 5 (highest).')),
                ('min_horizon_months', models.PositiveSmallIntegerField(default=0)),
                ('liquid', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['risk_level', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('risk_level__gte', 1), ('risk_level__lte', 5)), name='product_risk_level_1_to_5')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateField()),
                ('amount', models.BigIntegerField(help_text='Positive: income, negative: expense (HUF).')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('own_transfer', models.BooleanField(default=False, help_text="Between the customer's own accounts or a SaverAI transfer; ignored in surplus.")),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.account')),
            ],
            options={
                'ordering': ['booked_on', 'id'],
            },
        ),
    ]
